title = "Chess Programming Wiki"
baseurl = "/"
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
# disableKinds = ["taxonomy", "term"]
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
languageCode = "en-US"
rssLimit = 10
summarylength = 20 # 70 (default)

# Multilingual
defaultContentLanguage = "en"
disableLanguages = ["de", "nl"]
defaultContentLanguageInSubdir = false

copyRight = "Copyright (c) 2023 Hyas"

[build.buildStats]
  enable = true

[social]
  twitter = "getdoks"

[outputs]
  home = ["HTML", "RSS", "searchIndex"]
  section = ["HTML", "RSS", "SITEMAP"]

[outputFormats.searchIndex]
  mediaType = "application/json"
  baseName = "search-index"
  isPlainText = true
  notAlternative = true

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "30m"

[taxonomies]
  contributor = "contributors"
  category = "categories"
  tag = "tags"

[minify.tdewolff.html]
  keepWhitespace = false

[related]
  threshold = 80
  includeNewer = true
  toLower = false
    [[related.indices]]
    name = "categories"
    weight = 100
    [[related.indices]]
    name = "tags"
    weight = 80
    [[related.indices]]
    name = "date"
    weight = 10

[imaging]
  anchor = "Smart"
  bgColor = "#ffffff"
  hint = "photo"
  quality = 75
  resampleFilter = "Box"
