[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18.16.1"
  NPM_VERSION = "9.5.1"

[context.production]
  command = "pnpm build"

[context.deploy-preview]
  command = "pnpm build -- -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "pnpm build -- -b $DEPLOY_PRIME_URL"

[context.next]
  command = "pnpm build"

[context.next.environment]
  HUGO_ENV = "next"

[dev]
  framework = "#custom"
  command = "pnpm dev"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

# Redirects and rewrites — https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=100; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin"
    Permissions-Policy = "geolocation=(self), microphone=(), camera=()"
    Cache-Control= '''
    public,
    max-age=100'''
    Access-Control-Allow-Origin = "*"

[functions."fetch-wiki-content"]
  schedule = "@daily"